#!/usr/bin/env bash

# argument 1 is the filename w/o extension, argument 2 is the make command.
#  valid make commands are: "" | "run" | "run_only"

# Die when an error happens.

set -e

if [ $# -eq 0 ]; then
	echo "Usage: bld <filename w/o extension> [run|run_only]"
	echo
	echo " run      - build the executable and then run it"
	echo " run_only - run previously-built executable"
	exit 0;
fi

cmd="make main_filename=$1 $2"
eval "$cmd"
